apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpnext-maintenance-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: erpnext-maintenance-operator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    resourceNames:
      - dev-erpnext
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: erpnext-maintenance-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: erpnext-maintenance-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: erpnext-maintenance-operator
