apiVersion: v1
kind: PersistentVolume
metadata:
  name: erpnext-sites-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: erpnext-local
  hostPath:
    path: /data-disk/erpnext-sites
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erpnext-sites
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: erpnext-local
  resources:
    requests:
      storage: 100Gi
