image:
  repository: frappe/erpnext
  tag: v16.20.1
  pullPolicy: IfNotPresent

persistence:
  worker:
    enabled: true
    existingClaim: erpnext-sites
    accessModes:
      - ReadWriteOnce

mariadb-sts:
  enabled: false

mariadb-subchart:
  enabled: false

postgresql-sts:
  enabled: false

postgresql-subchart:
  enabled: false

dbHost: mariadb
dbPort: "3306"
dbRootUser: root

dbExistingSecret: erpnext-keyvault-secrets
dbExistingSecretPasswordKey: db-root-password

ingress:
  enabled: true

  ingressName: dev-erpnext

  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: dev-erpnext.uxe.ai
      paths:
        - path: /
          pathType: Prefix
